[workspace]
authors = ["Robert Cocker <rcocker87@gmail.com>"]
channels = ["conda-forge",  "https://conda.modular.com/max-nightly/", "https://repo.prefix.dev/modular-community"]
name = "version-cv"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
datasets = ">=3.6.0,<4"
transformers = ">=4.53.2,<5"
tensorflow = ">=2.18.0,<3"
jupyter = ">=1.1.1,<2"
notebook = ">=7.4.4,<8"
jax = ">=0.5.2,<0.6"
jaxlib = ">=0.5.2,<0.6"
keras = ">=3.10.0,<4"
tensorflow-cpu = ">=2.18.0,<3"
dm-tree = ">=0.1.9,<0.2"
regex = ">=2024.11.6,<2025"
kagglehub = ">=0.3.8,<0.4"
sentencepiece = ">=0.2.0,<0.3"
sympy = ">=1.14.0,<2"
matplotlib = ">=3.10.3,<4"
seaborn = ">=0.13.2,<0.14"
pandas = ">=2.3.1,<3"
spacy = ">=3.8.7,<4"
tqdm = ">=4.67.1,<5"
orjson = ">=3.11.0,<4"
accelerate = ">=1.8.1,<2"
bitsandbytes = ">=0.46.1,<0.47"
einops = ">=0.8.1,<0.9"
joblib = ">=1.5.1,<2"
scikit-learn = ">=1.7.0,<2"
numpy = ">=1.26.4,<2"
psutil = ">=7.0.0,<8"
nbconvert = ">=7.16.6,<8"
max = ">=25.3.0.dev2025032405,<26"
jupytext = ">=1.17.2,<2"
python = ">=3.12.11,<3.13"
max-pipelines = ">=25.3.0.dev2025032405,<26"
pip = ">=25.1.1,<26"
lxml = ">=6.0.0,<7"
pylatex = ">=1.4.2,<2"
latexmk = ">=4.87,<5"
attrs = ">=25.3.0,<26"
pdf2image = ">=1.17.0,<2"
tesseract = ">=5.5.1,<6"
pytesseract = ">=0.3.13,<0.4"
statsmodels = ">=0.14.5,<0.15"
pandoc = ">=3.7.0.2,<4"
pyarrow = ">=19.0.1,<20"
pyspark = ">=4.0.0,<5"
apache-atlas = ">=0.0.16,<0.0.17"
pypandoc = ">=1.15,<2"
scipy = ">=1.16.0,<2"

[pypi-dependencies]
keras-nlp = ">=0.21.1, <0.22"
keras-hub = ">=0.21.1, <0.22"
tf-keras = ">=2.18.0, <3"
flax = ">=0.10.6, <0.11"
apache-airflow = ">=3.0.3, <4"
pyflink = ">=1.0, <2"
spark-nlp = ">=6.0.5, <7"
fastapi = { version = "*", extras = ["standard"] }
