[workspace]
authors = ["Robert Cocker <rcocker87@gmail.com>"]
channels = ["conda-forge",  "https://conda.modular.com/max-nightly/", "https://repo.prefix.dev/modular-community"]
name = "version-cv"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
datasets = ">=4.4.1,<5"
transformers = ">=4.57.3,<5"
tensorflow = ">=2.19.1,<3"
jupyter = ">=1.1.1,<2"
notebook = ">=7.5.0,<8"
jax = ">=0.7.2,<0.8"
jaxlib = ">=0.7.2,<0.8"
keras = ">=3.12.0,<4"
tensorflow-cpu = ">=2.19.1,<3"
dm-tree = ">=0.1.9,<0.2"
regex = ">=2025.11.3,<2026"
kagglehub = ">=0.3.13,<0.4"
sentencepiece = ">=0.2.0,<0.3"
sympy = ">=1.14.0,<2"
matplotlib = ">=3.10.8,<4"
seaborn = ">=0.13.2,<0.14"
pandas = ">=2.3.3,<3"
spacy = ">=3.8.11,<4"
tqdm = ">=4.67.1,<5"
orjson = ">=3.11.4,<4"
accelerate = ">=1.12.0,<2"
bitsandbytes = ">=0.48.2,<0.49"
einops = ">=0.8.1,<0.9"
joblib = ">=1.5.2,<2"
scikit-learn = ">=1.8.0,<2"
numpy = ">=2.3.5,<3"
psutil = ">=7.1.3,<8"
nbconvert = ">=7.16.6,<8"
max = ">=26.1.0.dev2025121405,<27"
jupytext = ">=1.18.1,<2"
python = ">=3.12.12,<3.13"
max-pipelines = ">=26.1.0.dev2025121405,<27"
pip = ">=25.3,<26"
lxml = ">=6.0.2,<7"
pylatex = ">=1.4.2,<2"
latexmk = ">=4.87,<5"
attrs = ">=25.4.0,<26"
pdf2image = ">=1.17.0,<2"
tesseract = ">=5.5.1,<6"
pytesseract = ">=0.3.13,<0.4"
statsmodels = ">=0.14.6,<0.15"
pandoc = ">=3.8.3,<4"
pyarrow = ">=22.0.0,<23"
pyspark = ">=4.0.1,<5"
apache-atlas = ">=0.0.16,<0.0.17"
pypandoc = ">=1.16.2,<2"
scipy = ">=1.16.3,<2"
bandit = ">=1.9.2,<2"
pip-audit = ">=2.10.0,<3"
pytest = ">=9.0.2,<10"
xgboost = ">=3.1.2,<4"
ipykernel = ">=7.1.0,<8"
btop = ">=1.4.5,<2"

[pypi-dependencies]
keras-nlp = ">=0.24.0, <0.25"
keras-hub = ">=0.24.0, <0.25"
tf-keras = ">=2.19.0, <3"
flax = ">=0.12.0, <0.13"
apache-airflow = ">=3.1.0, <4"
pyflink = ">=1.0, <2"
spark-nlp = ">=6.2.3, <7"
toml-to-requirements = ">=0.3.0, <0.4"
gensim = ">=4.4.0, <5"
